import 'package:flutter/material.dart';

class TextStyleRes {
  TextStyle base = TextStyle(fontFamily: "NanumSquare", fontSize: 15);
  TextStyle base7_700 = TextStyle(fontFamily: "NanumSquare", fontSize: 7, fontWeight: FontWeight.w700);
  TextStyle base10 = TextStyle(fontFamily: "NanumSquare", fontSize: 10);
  TextStyle base10_800 = TextStyle(fontFamily: "NanumSquare", fontSize: 10, fontWeight: FontWeight.w800);
  TextStyle base11_700 = TextStyle(fontFamily: "NanumSquare", fontSize: 11, fontWeight: FontWeight.w700);
  TextStyle base11_700U = TextStyle(fontFamily: "NanumSquare", fontSize: 11, fontWeight: FontWeight.w700, decoration: TextDecoration.underline);
  TextStyle base12 = TextStyle(fontFamily: "NanumSquare", fontSize: 12);
  TextStyle base12_100 = TextStyle(fontFamily: "NanumSquare", fontSize: 12, fontWeight: FontWeight.w100);
  TextStyle base12_100U = TextStyle(fontFamily: "NanumSquare", fontSize: 12, fontWeight: FontWeight.w100, decoration: TextDecoration.underline);
  TextStyle base12_700 = TextStyle(fontFamily: "NanumSquare", fontSize: 12, fontWeight: FontWeight.w700);
  TextStyle base12_700U = TextStyle(fontFamily: "NanumSquare", fontSize: 12, fontWeight: FontWeight.w700, decoration: TextDecoration.underline);
  TextStyle base12grey = TextStyle(fontFamily: "NanumSquare", fontSize: 12, color: Color(0xffb9b9b9));
  TextStyle base12Sgrey = TextStyle(fontFamily: "NanumSquare", fontSize: 12, decoration: TextDecoration.lineThrough, color: Color(0xffb9b9b9));
  TextStyle base12_700gold = TextStyle(fontFamily: "NanumSquare", fontSize: 12, fontWeight: FontWeight.w700, color: Color(0xffae946c));
  TextStyle base13 = TextStyle(fontFamily: "NanumSquare", fontSize: 13);
  TextStyle base13_100 = TextStyle(fontFamily: "NanumSquare", fontSize: 13, fontWeight: FontWeight.w100);
  TextStyle base13_700U = TextStyle(fontFamily: "NanumSquare", fontSize: 13, fontWeight: FontWeight.w700, decoration: TextDecoration.underline);
  TextStyle base13gold = TextStyle(fontFamily: "NanumSquare", fontSize: 13, color: Color(0xffae946c));
  TextStyle base13grey = TextStyle(fontFamily: "NanumSquare", fontSize: 13, color: Color(0xffbbbbbb));
  TextStyle base13Red = TextStyle(fontFamily: "NanumSquare", fontSize: 13, color: Color(0xffff5555));
  TextStyle base13_700gold = TextStyle(fontFamily: "NanumSquare", fontSize: 13, fontWeight: FontWeight.w700, color: Color(0xffae946c));
  TextStyle base14 = TextStyle(fontFamily: "NanumSquare", fontSize: 14);
  TextStyle base14gold = TextStyle(fontFamily: "NanumSquare", fontSize: 14, color: Color(0xffae946c));
  TextStyle base14white = TextStyle(fontFamily: "NanumSquare", fontSize: 14, color: Color(0xffffffff));
  TextStyle base14_100 = TextStyle(fontFamily: "NanumSquare", fontSize: 14, fontWeight: FontWeight.w100);
  TextStyle base14_700 = TextStyle(fontFamily: "NanumSquare", fontSize: 14, fontWeight: FontWeight.w700);
  TextStyle base14_100U = TextStyle(fontFamily: "NanumSquare", fontSize: 14, fontWeight: FontWeight.w100, decoration: TextDecoration.underline);
  TextStyle base14_700U = TextStyle(fontFamily: "NanumSquare", fontSize: 14, fontWeight: FontWeight.w700, decoration: TextDecoration.underline);
  TextStyle base15 = TextStyle(fontFamily: "NanumSquare", fontSize: 15);
  TextStyle base15_700 = TextStyle(fontFamily: "NanumSquare", fontSize: 15, fontWeight: FontWeight.w700);
  TextStyle base15white = TextStyle(fontFamily: "NanumSquare", fontSize: 15, color: Color(0xffffffff));
  TextStyle base15_700white = TextStyle(fontFamily: "NanumSquare", fontSize: 15, fontWeight: FontWeight.w700, color: Color(0xffffffff));
  TextStyle base16 = TextStyle(fontFamily: "NanumSquare", fontSize: 16);
  TextStyle base16_700 = TextStyle(fontFamily: "NanumSquare", fontSize: 16, fontWeight: FontWeight.w700);
  TextStyle base16_800 = TextStyle(fontFamily: "NanumSquare", fontSize: 16, fontWeight: FontWeight.w800);
  TextStyle base18 = TextStyle(fontFamily: "NanumSquare", fontSize: 18);
  TextStyle base18_100 = TextStyle(fontFamily: "NanumSquare", fontSize: 18, fontWeight: FontWeight.w100);
  TextStyle base20 = TextStyle(fontFamily: "NanumSquare", fontSize: 20);
  TextStyle base20white = TextStyle(fontFamily: "NanumSquare", fontSize: 20, color: Color(0xffffffff));
  TextStyle base24 = TextStyle(fontFamily: "NanumSquare", fontSize: 24);
  TextStyle base25 = TextStyle(fontFamily: "NanumSquare", fontSize: 25);
  TextStyle base25white = TextStyle(fontFamily: "NanumSquare", fontSize: 25, color: Color(0xffffffff));
  TextStyle baseXL = TextStyle(fontFamily: "NanumSquare", fontSize: 25);
  TextStyle baseBold = TextStyle(fontFamily: "NanumSquare", fontSize: 15, fontWeight: FontWeight.w700);
  TextStyle baseLargeBold = TextStyle(fontFamily: "NanumSquare", fontSize: 20, fontWeight: FontWeight.w700);
  TextStyle baseWhite = TextStyle(fontFamily: "NanumSquare", fontSize: 15, color: Color(0xffffffff));
  TextStyle baseGrey = TextStyle(fontFamily: "NanumSquare", fontSize: 15, color: Color(0xff888888));

  TextStyle dots = TextStyle(fontFamily: "5x5Dots", fontSize: 12);
  TextStyle dots10 = TextStyle(fontFamily: "5x5dots", fontSize: 10);
  TextStyle dots15 = TextStyle(fontFamily: "5x5dots", fontSize: 15);
  TextStyle dots20 = TextStyle(fontFamily: "5x5Dots", fontSize: 20);
  TextStyle dots24 = TextStyle(fontFamily: "5x5Dots", fontSize: 24);
}